### ISSUE TITLE
Add a build tool as Maven or Gradle so that we can built it.

### ISSUE THREAD

**Issue by HydrolienF** [ZockerAxel/CrazyAdvancementsAPI#14]

**Comment by HydrolienF** [comment]
It seem's to be an icredible plugin, but I can't use it in my plugin as a dependency

**Comment by ZockerAxel** [comment]
The problem is you can't build it without nms, and there is no public nms repo so I cannot provida a build tool to make it easily buildable because it will have missing dependencies no matter what. There is a pom file included in one of the downloads so you can clone the API into a local maven repo that you can depend on.

See the discord for more information.

**Comment by HydrolienF** [comment]
ok I understand.
