### ISSUE TITLE
Upgrade to utilise Adventure

### ISSUE THREAD

**Issue by Greenfoot5** [ZockerAxel/CrazyAdvancementsAPI#20]
net.md_5.bungee.api.chat is depreciated in the latest versions of paper, instead it utilises Adventure and it's components: https://docs.papermc.io/paper/dev/component-api/introduction

It would be good if this plugin supported these types of components.

**Comment by ZockerAxel** [comment]
This API is for Spigot, and I do not officially support Paper or any other Spigot fork.
The only reason the API depends on paperweight is because Spigot does not provide a way to depend on NMS (at least no legal way i know of).

There will be no support for any features that are not from the Spigot API (or NMS). Period.

Feel free to fork the project if you want to add support for features like that.

**Comment by Greenfoot5** [comment]
Fair enough. I however wouldn't feel comfortable forking and attempting any work without a license however.
