### ISSUE TITLE
How to make a criteria (not a bug, a question ;-;)

### ISSUE THREAD

**Issue by VickyE2** [ZockerAxel/CrazyAdvancementsAPI#21]
So i was trying to use the API it was all going smoothly but then from the documentation i couldn't quite understand the Criteria System and how to grant a user an advancement. this is what was in the documentation:
`advacnement.setCriteria(new Criteria(new String[] {"a", "b", "c"}, new String[][] {{"a", "b"}, {"c"}}););`
what are a b and c? are the mean to be things like this: `return new Criteria(new String[] {"trigger: minecraft:shot_crossbow"}, new String[][] {{"a"}});`: A trigger from minecraft? Because im quite lost. I wouldn't have posted this as an issue but i couldn't find anyother way to contac you ;-; sorry.

**Comment by ZockerAxel** [comment]
Please do not open github issues for questions.

I will answer this one time to fix your issue but this is not the place for questions. Please use the discord server or the spigot discussion for questions.

The criteria system is string-based. "a", "b" and "c" are just examples, you can use any string you want. You can then later grant each criterion by it's string that you set. The Criteria constructor first takes an array of all possible criteria and then a nested array that describes the combination of criteria you need. There is no connection to minecrafts trigger system, you cannot use it to grant these advancements. You should just make a datapack instead of using an API if you want to use minecrafts triggers.

**Comment by VickyE2** [comment]
Oh thank you in sorry ;-;
